application: angularbeef
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /libs
  static_dir: libs

- url: /static
  static_dir: static

- url: /includes
  static_dir: templates/includes

- url: /signup
  script: angularbeef.app
  secure: always

- url: /login
  script: angularbeef.app
  secure: always

- url: /.*
  script: angularbeef.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest

- name: markupsafe                                                              
  version: latest

- name: webapp2
  version: "2.5.1"

- name: PIL
  version: "1.1.7"